### ISSUE TITLE
Implement Router contract

### ISSUE THREAD

**Issue by FaisalAl-Tameemi** [subslice/game-theory#3]
The Router contract must enable the instantiation of a Game (another contract) via an exposable method.

---

2 approaches:

a. Instantiate and reference within Router
b. Instantiate outside Router, reference in Router

---

Outcomes:

- [ ] Can instantiate a game from the Router in an E2E test of the router contract (using the contract hash)
- [ ] Instantiation should emit an event with the contract hash and address (add to common `Traits` crate)
- [ ] Can get the status of a game from the Router given the game contract's address
- [ ] Has E2E tests for the router

**Comment by a-moreira** [comment]
done, will be improved in the following iterations
